# Generated by Django 2.2.6 on 2020-10-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201016_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='group',
            field=models.CharField(blank=True, choices=[('Test group', 'Test group'), ('Second group', 'Second group'), ('Third group', 'Third group')], max_length=100),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
