# Generated by Django 2.2.6 on 2020-10-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201016_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
