# Generated by Django 2.2.6 on 2020-10-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_delete_newpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Список постов'},
        ),
    ]
