# Generated by Django 2.2.6 on 2020-11-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20201111_1024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
