# Generated by Django 2.2.6 on 2020-10-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201015_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
