# Generated by Django 2.2.6 on 2020-10-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201015_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
